name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
     - 'README.md'

  pull_request:
    branches: 
      - master
    paths-ignore:
      - 'README.md'

jobs:
  test:
    if: "contains(github.event.commits[0].message, '[ci skip]') == false || contains(github.event.commits[0].message, '[skip ci]') == false"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']
        gemfile:
          - gemfiles/Gemfile.rails-5.2.4.4

          - gemfiles/Gemfile.rails-6.0.3.4

    steps:
      - uses: actions/checkout@v2
        name: Set up Ruby

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake
